spring.application.name=demo

spring.datasource.url=jdbc:sqlserver://localhost:8080;databaseName=academia;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=*123456HAS*

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

