spring.application.name=demo
spring.datasource.url=jdbc:sqlserver://localhost:8080;databaseName=Academia;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=*123456HAS*
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true